- name: Build and Test

  on:
    push:
      branch:
        - 'master'

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 8
          uses: actions/setup-java@v1
          with:
            java-version: 8
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build Project
          run: bash ./gradlew :presentation:assembleDebug, :domain:assembleDebug, :data:assembleDebug, :app:assembleDebug

    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 8
          uses: actions/setup-java@v1
          with:
            java-version: 8
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Test Project
          run: ./gradlew :domain:testDebugUnitTest


